---
- name: Upload disk space notify config
  template:
    src: "{{ role_path }}/templates/disk-space-notify.conf.j2"
    dest: "{{ disk_space_notify_conf_path }}"
    backup: true
    owner: root
    group: root
    mode: '0644'

- name: Upload disk space notify script
  template:
    src: "{{ role_path }}/templates/disk-space-notify.sh.j2"
    dest: "{{ disk_space_notify_script_path }}"
    backup: false
    owner: root
    group: root
    mode: '0755'

- name: Create disk space notify cron job
  cron:
    name: Check on disk space every X hours. See /etc/disk-space-notify.conf for options.
    day: '{{ disk_space_notify_cron_day }}'
    hour: '{{ disk_space_notify_cron_hour }}'
    minute: '{{ disk_space_notify_cron_minute }}'
    user: '{{ disk_space_notify_cron_owner }}'
    job: "{{ disk_space_notify_script_path }}"

# @TODO: Check for and warn about duplicate cron jobs, in cases where the playbook has been switched from the makeifle version to this role
# If orginal defaults were not modified, only the comment will be duplciated, which is not a problem.
# If the job was adjusted from defaults, ansible will create a 2nd job, which is undesireable.
