---
- name: Upload disk space notify config
  template:
    src: /templates/disk-space-notify.conf.j2
    dest: "{{ disk_space_notify_conf_path }}"
    backup: true
    owner: root
    group: root
    mode: '0644'

- name: Upload disk space notify script
  template:
    src: /templates/disk-space-notify.sh.j2
    dest: "{{ disk_space_notify_script_path }}"
    backup: false
    owner: root
    group: root
    mode: '0755'

- name: Create disk space notify cron job
  cron:
    name: Check on disk space every X hours. See /etc/disk-space-notify.conf for options.
    day: '{{ disk_space_notify_cron_day }}'
    hour: '{{ disk_space_notify_cron_hour }}'
    minute: '{{ disk_space_notify_cron_minute }}'
    owner: '{{ disk_space_notify_cron_owner }}'
    job: "{{ disk_space_notify_script_path }}"

# @TODO: Warn about duplicate jobs? Ansible will create a 2nd job if the role was switched from the old makefile installer to this role.
