---
- hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Initialize apt cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install role dependencies
      apt:
          name:
            - cron
            - mailutils
          state: present
      when: ansible_os_family == "Debian"
