---
on:
  pull_request:
    branches:
      - main

jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - name: Molecule
        uses: robertdebock/molecule-action@4.0.9
        env:
          ANSIBLE_FORCE_COLOR: '1'
